name = "Ghostcraft"
author = "klepti"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6956c3e6956bb265c1fb331ba642b9425594fbb2021606f85c7747b0ab0981a8"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
