name = "Ghostcraft"
author = "klepti"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc897f7a87156aa4d2e3b28c92d583899a60c6c5bd125d86131854a71f7ffd13"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
