name = "Ghostcraft"
author = "klepti"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07ca3776c2b211f18510cb565712d6eb463bacad36f85ea5953554eb4042d5bb"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
