name = "Ghostcraft"
author = "klepti"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4e67e4445cc21bc6f51b3bc5d081464f547cb58f03e8c4982692e8a99b54b14"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
