name = "Ghostcraft"
author = "klepti"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f0213f4d5ea3245ee83cd355f580acaa3887d81d381f831c584e109a72b666f"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
