name = "Ghostcraft"
author = "klepti"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "401cd6b73210762e04a0f545e99b8bcc7a4f68ce22d6e0be10812496e5870e85"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
