name = "Ghostcraft"
author = "klepti"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f4b0f98c4b0d71bb48121f5b6256715d45765a1684933fa6c4553f25feca4b4"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
