name = "Ghostcraft"
author = "klepti"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4eb254d69c53aabfdad91021d4204bf7e3e36ef9bd6d2c472588f965dde9332"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
