name = "Ghostcraft"
author = "klepti"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a2c682346a494647d654c20dd831acbff34063a9fe4085cd304f79d9f314f91"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
