name = "Ghostcraft"
author = "klepti"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4a508c692ef3997d97792ec5a5ef309dfeb21a1396ba235fe169e0041310299"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
