name = "Ghostcraft"
author = "klepti"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aa6c0670fd43d7dda9c1b0b811ca6740f81153a66dad1a3a02e45c693208f5f"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
